# Generated by Django 3.0.4 on 2020-03-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200305_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='homeAddress',
            field=models.CharField(default='N/A', max_length=255, null=True),
        ),
    ]
