# Generated by Django 3.0.3 on 2020-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20200306_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='case',
            field=models.CharField(blank=True, choices=[('Dengue', 'Dengue'), ('Cleaning', 'Cleaning')], max_length=20, null=True),
        ),
    ]
