# Generated by Django 3.0.3 on 2020-03-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='case',
            field=models.CharField(blank=True, choices=[('Dengue', 'Dengue'), ('Cleaning', 'Cleaning'), ('Corona Virus', 'Corona Virus')], max_length=20, null=True),
        ),
    ]
