# Generated by Django 3.0.4 on 2020-03-05 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='N/A', max_length=100, null=True)),
                ('lastName', models.CharField(default='N/A', max_length=100, null=True)),
                ('firstName', models.CharField(default='N/A', max_length=100, null=True)),
                ('middleName', models.CharField(default='N/A', max_length=100, null=True)),
                ('birthDate', models.CharField(default='N/A', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20)),
                ('maritalStatus', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Legally Seperated', 'Legally Seperated'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('mobile_number', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$')])),
                ('email', models.EmailField(max_length=100, null=True)),
                ('ward', models.CharField(blank=True, choices=[('SH-102', 'SH-102'), ('SH-101', 'SH-101'), ('SH-201', 'SH-201')], max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
